from .cadastroDeFuncionario import bp as cadastroDeFuncionario_bp
from .carteiradigital import bp as carteiradigital_bp
from .esqueci_senha import bp as esqueci_senha_bp
from .index import bp as index_bp
from .login import bp as login_bp
from .logout import bp as logout_bp
from .registrarUsuario import bp as registrarUsuario_bp
from .selecionarDadosCadastrais import bp as selecionarDadosCadastrais_bp
from .powerBI import bp as powerBI_bp